### ISSUE TITLE
carla_ros_bridge-2 dies when launching baseline (AttributeError: 'CarlaRosBridge' object has no attribute 'sync_mode)

### ISSUE THREAD

**Issue by EthanJamesLew** [PoPGRI/Race#16]
**Describe the bug**
I am not able to run the baseline solution with the docker container. When doing the roslaunch command, I receive the error
```
carla@elew-workstation:~/graic-workspace$ roslaunch race carla_single.launch num_wheels:=4 model_type:=model_free
... logging to /home/carla/.ros/log/0b97d7f8-73d5-11ec-8aec-28dfeb5ccd62/roslaunch-elew-workstation-976.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://elew-workstation:36381/

SUMMARY
========

PARAMETERS
 * /carla_ros_bridge/ego_vehicle_role_name: ["hero", "ego_veh...
 * /carla_ros_bridge/fixed_delta_seconds: 
 * /carla_ros_bridge/host: localhost
 * /carla_ros_bridge/passive: False
 * /carla_ros_bridge/port: 2000
 * /carla_ros_bridge/synchronous_mode: 
 * /carla_ros_bridge/synchronous_mode_wait_for_vehicle_control_command: 
 * /carla_ros_bridge/timeout: 10
 * /carla_ros_bridge/town: t1_triple
 * /race_run/N: 1
 * /race_run/log: /tmp/
 * /race_run/model_type: model_free
 * /race_run/num_wheels: 4
 * /race_run/track: t1_triple
 * /rosdistro: noetic
 * /rosversion: 1.15.9
 * /use_sim_time: True

NODES
  /
    carla_ros_bridge (carla_ros_bridge/bridge.py)
    race_run (race/run.py)
    spawn_npc (race/spawn_npc.py)

auto-starting new master
process[master]: started with pid [984]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 0b97d7f8-73d5-11ec-8aec-28dfeb5ccd62
process[rosout-1]: started with pid [994]
started core service [/rosout]
process[carla_ros_bridge-2]: started with pid [1001]
process[race_run-3]: started with pid [1002]
process[spawn_npc-4]: started with pid [1003]
[INFO] [1642011941.685030, 0.000000]: Trying to connect to localhost:2000
[INFO] [1642011942.009282, 0.000000]: Loading town 't1_triple' (previous: 'Town03').
WARNING: cannot parse georeference: ''. Using default values. 
WARNING: cannot parse georeference: ''. Using default values. 
[INFO] [1642011944.015371, 0.000000]: synchronous_mode: 
Traceback (most recent call last):
  File "/home/carla/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 485, in <module>
    main()
  File "/home/carla/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 468, in main
    carla_bridge.initialize_bridge(carla_client.get_world(), parameters)
  File "/home/carla/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 114, in initialize_bridge
    self.carla_settings.synchronous_mode = self.parameters["synchronous_mode"]
Boost.Python.ArgumentError: Python argument types in
    None.None(WorldSettings, str)
did not match C++ signature:
    None(carla::rpc::EpisodeSettings {lvalue}, bool)
[INFO] [1642011944.080798, 0.000000]: Shutting down...
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 572, in signal_shutdown
    h()
  File "/home/carla/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 374, in destroy
    if not self.sync_mode:
AttributeError: 'CarlaRosBridge' object has no attribute 'sync_mode'
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
ERROR: Spawn failed because of collision at spawn position
================================================================================REQUIRED process [carla_ros_bridge-2] has died!
process has died [pid 1001, exit code 1, cmd /home/carla/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py __name:=carla_ros_bridge __log:=/home/carla/.ros/log/0b97d7f8-73d5-11ec-8aec-28dfeb5ccd62/carla_ros_bridge-2.log].
log file: /home/carla/.ros/log/0b97d7f8-73d5-11ec-8aec-28dfeb5ccd62/carla_ros_bridge-2*.log
Initiating shutdown!
================================================================================
[spawn_npc-4] killing on exit
[race_run-3] killing on exit
[carla_ros_bridge-2] killing on exit
```

**To Reproduce**
The main README.md instructions up until `roslaunch race carla_single.launch num_wheels:=4 model_type:=model_free`.

**Expected behavior**
A vehicle should appear in the CARLA window. 

**Screenshots**
![error_screen](https://user-images.githubusercontent.com/15683738/149200390-d5a43bf0-d060-4eeb-936d-629aa5a50f64.png)

**Related Context (please complete the following information):**
 - GRAIC Version latest in docker--GRAIC 0.1.0
 - Map Version t1_triple
 - Car Model model_free

**Comment by EthanJamesLew** [comment]
I got it working in another environment.
